### ISSUE TITLE
parameters

### ISSUE THREAD

**Issue by MatthieuLamp** [miyako/4d-plugin-ica#2]
Hi
what parameters for ICA SCAN ?

**Comment by miyako** [comment]
in general you can find the parameter types in ``manifest.json``

https://github.com/miyako/4d-plugin-ica/blob/master/ICA/manifest.json

you can also look at ``documentation.htm``

or open the sample database

**Comment by MatthieuLamp** [comment]
4D v18 crashes when opening the base

**Comment by miyako** [comment]
I am sorry I do not reproduce a crash like you describe.
Catalina 10.15.3, v18 248942

can you elaborate what you did and what exactly happened?

**Comment by miyako** [comment]
for what it's worth, I have posted a refactored (project mode) version today.

**Comment by MatthieuLamp** [comment]
it's ok, thanks
